module.exports = {
  preset: 'jest-expo',
  testEnvironment: 'node',
  setupFiles: ['<rootDir>/jest.setup.js'],
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|@react-navigation|expo|@expo|expo-.*|@expo/.*|sentry-expo|react-native-toast-message)/)',
  ],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/#1/',
    '/backup/',
    '/\\.manus-work/',
    '/_agent/',
    '/diagnostics/',
    '/artifacts/',
    '/_reports/',
    '/backend/',
    '/tools/accountability/',
    '/App.test.js',
  ],
  modulePathIgnorePatterns: [
    '<rootDir>/#1/',
    '<rootDir>/backup/',
    '<rootDir>/\\.manus-work/',
    '<rootDir>/_agent/',
    '<rootDir>/diagnostics/',
    '<rootDir>/artifacts/',
    '<rootDir>/_reports/',
    '<rootDir>/backend/',
    '<rootDir>/tools/accountability/',
  ],
};
